### PR TITLE
review web page

### PR DESCRIPTION
**Pull request by Vovan707**

### CODE REVIEW

**Comment by Vovan707** [comment]
@sergeyradkevich review please

**Comment by sergeyradkevich** [comment]
Hey @Vovan707, can you please check this PR, as I do not see changes, just one commit.

**Comment by sergeyradkevich** [comment]
@Vovan707 Can you please think of a proper name for this project (repository), not just HTML project, but something is related with what it stands for? For example, Favorite Places, Your Locations, ext.

**Comment by Vovan707** [comment]
@sergeyradkevich  review please

**Comment by sergeyradkevich** [comment]
@Vovan707 Something is still wrong. I just see a few commits. 
I expect to see all the things you done from the beginning within this pull request. Please take a look at [the changes](https://github.com/Vovan707/Favorite-Places/pull/1/files) that are present here.

**Comment by Vovan707** [comment]
@sergeyradkevich Ouu..i don't know about this problem ((

**Comment by sergeyradkevich** [comment]
@Vovan707 I believe you have been committing the things into `master` directly from the beginning. You misremembered [GitHub Flow](https://guides.github.com/introduction/flow/). You should not push to `master` directly, instead you should create a branch and then send a pull request.

**Comment by Vovan707** [comment]
@sergeyradkevich  exactly , but now I need a new repository is to do it? Will re- add

**Comment by sergeyradkevich** [comment]
@Vovan707 Considering that it is own free repository you can do so. But if it is a customer repository, you would have troubles :)

Please do not forget to remove the old one.

**Pull request closed without merging**
